version: "3"
services:
  strider:
    image: ${PROJECT_DOCKER_IMAGE}
    ports:
      - "80:4884"
    tty: true
    networks:
      - driveon-webnet
    environment:
      - NODE_ENV=production
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '0.2'
          memory: 300M
      restart_policy:
        condition: on-failure
networks:
  driveon-webnet:
